### ISSUE TITLE
Freezing → Auto-closing | when opening files fast

### ISSUE THREAD

**Issue by nitin2953** [QL-Win/QuickLook#1015]
**Describe the bug**
I'm opening 4000w-8000w, 3MB-8MB images
after opening files one-by-one (fast)/highlighting them in Explorer, it feeze (nothing work) close automatically after some times

**Expected behavior**
it should just work

**Desktop (please complete the following information):**
 - OS Version: Windows 10 21H1 (19043.1110)
 - QuickLook Version: 3.7.0 from github msi

**Screenshots and Exception Log**
![Screenshot 2021-10-11 182335](https://user-images.githubusercontent.com/34852979/136797475-7fbf3988-17da-4a81-87c6-017c5a583d0a.png)

**Comment by nitin2953** [comment]
where is logfile

**Comment by rabelux** [comment]
It's written in the issue template.

**Comment by nitin2953** [comment]
```
========12-Oct-21 11:55:34 AM========
System.ArgumentNullException: Value cannot be null.
Parameter name: pixels
   at System.Windows.Media.Imaging.CachedBitmap..ctor(Int32 pixelWidth, Int32 pixelHeight, Double dpiX, Double dpiY, PixelFormat pixelFormat, BitmapPalette palette, Array pixels, Int32 stride)
   at ImageMagick.IMagickImageExtentions.ToBitmapSource[TQuantumType](IMagickImage`1 self, Boolean useDensity)
   at QuickLook.Plugin.ImageViewer.AnimatedImage.Providers.ImageMagickProvider.<>c__DisplayClass2_0.<GetRenderedFrame>b__0()

========12-Oct-21 11:55:34 AM========
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Media.MediaContext.CreateChannels()
   at System.Windows.Media.MediaSystem.ConnectChannels(MediaContext mc)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.VisualTarget..ctor(HostVisual hostVisual)
   at QuickLook.Controls.BusyDecorator.VisualTargetPresentationSource..ctor(HostVisual hostVisual)
   at QuickLook.Controls.BusyDecorator.BackgroundVisualHost.ThreadedVisualHelper.CreateAndShowContent()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

========12-Oct-21 11:55:37 AM========
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at ImageMagick.ByteConverter.ToArray(IntPtr nativeData, Int32 length)
   at ImageMagick.PixelCollection.ToByteArray(Int32 x, Int32 y, Int32 width, Int32 height, String mapping)
   at ImageMagick.UnsafePixelCollection.ToByteArray(Int32 x, Int32 y, Int32 width, Int32 height, String mapping)
   at ImageMagick.PixelCollection.ToByteArray(String mapping)
   at ImageMagick.IMagickImageExtentions.ToBitmapSource[TQuantumType](IMagickImage`1 self, Boolean useDensity)
   at QuickLook.Plugin.ImageViewer.AnimatedImage.Providers.ImageMagickProvider.<>c__DisplayClass2_0.<GetRenderedFrame>b__0()
```
