### ISSUE TITLE
Crash when previewing large images

### ISSUE THREAD

**Issue by mbassalbioinformatics** [QL-Win/QuickLook#1054]
**Describe the bug**
When attempting to preview a large image file (png/jpg), quicklook crashes. It seems to be images larger than 10mb or so cause the crash.

**Expected behavior**
Ideally quicklook would handle images of all sizes to preview, or show and error that the image is too large to preview rather than crashing and closing.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 (multiple versions tested)
 - QuickLook Version: v0.3.7 (from installer)

**Comment by rabelux** [comment]
Did you mean version 3.7.1? Or 3.7.0?

**Comment by mbassalbioinformatics** [comment]
3.7.0 - only after posting did i realize there was a 3.7.1

**Comment by rabelux** [comment]
3.7.0 had a bug that caused crashes. Pls try 3.7.1 and reopen this ticket if issue persists.

**Comment by mbassalbioinformatics** [comment]
Hi again
Quicklook 3.7.1 still crashes when trying to open large png files >~3-4Mb in size

**Comment by rabelux** [comment]
If you'd provide an example file and logs that would be great.

**Comment by mbassalbioinformatics** [comment]
![1-2nucleosomes_wide](https://user-images.githubusercontent.com/42388216/145731407-5126cd61-a772-4f0d-910c-922cf9c1506c.png)

where can i find the log files after the crash?

**Comment by rabelux** [comment]
https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location

**Comment by mbassalbioinformatics** [comment]
The browser doesnt open the file but if you try to open it in even default windows viewer it opens fine. However, if the dev's dont want to look into the issue thats their choice. 

For reference the error in the log file shows
```
========19/09/2019 7:57:51 AM========
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at QuickLook.Plugin.OfficeViewer.IPreviewHandler.DoPreview()
   at QuickLook.Plugin.OfficeViewer.PreviewHandlerHost.Open(String path)
   at QuickLook.Plugin.OfficeViewer.Plugin.View(String path, ContextObject context)
   at QuickLook.ViewerWindow.<>c__DisplayClass5_0.<BeginShow>b__0()
```

**Comment by charles51679** [comment]
This large png file crashes on windows photo viewer and iPhone. Any tools to open with?

**Comment by mbassalbioinformatics** [comment]
It opens fine for me on windows photo viewer. It can also be opened in Gimp or Photoshop.

**Comment by mooflu** [comment]
The image dimensions are 45725 × 13901. When I open it in the debugger I get a "An unhandled exception of type 'System.OverflowException' occurred in PresentationCore.dll". A RGBA bitmap of that image with 4 bytes per pixel is going to be > 2.5G so I suspect some int32 overflow.
