### ISSUE TITLE
Not working with illegal characters in path to the file.

### ISSUE THREAD

**Issue by AlanEdd** [QL-Win/QuickLook#1197]
Looking at the file Quicklook.exception.log
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
```
if this could be fixed it would be great. Seems to be because all my files are within a OneDrive folder that has 'é' in the path. I can't change this as it's work that set the name of the One Drive default name. Therefore ALL files with have that character in the path to the file! 

If Quicklook could accomodate that it would be amazing. I tested it fine, once it's not on the path with illegal characters.

Thanks!

**Comment by rabelux** [comment]
Seems to be a duplicate of #1067 and/or #534

**Comment by AlanEdd** [comment]
Ok Apologies, I did a search for 'illegal' first.

**Comment by AlanEdd** [comment]
Any update on this or is it on a roadmap ? 
Quicklook won't work if é or a special character is in the path ? 

QuickLook v4.4.0.0
05/02/2026 09:34:08 Windows 10.0.26200.2
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
   at QuickLook.NativeMethods.QuickLook.ResolveShortcut(String path)
   at QuickLook.ViewWindowManager.TogglePreview(String path, String options)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by emako** [comment]
@AlanEdd  Maybe you can try running QuickLook in Asian languages using Locale_Remulator: [InWILL/Locale_Remulator](https://github.com/InWILL/Locale_Remulator)
