### ISSUE TITLE
QuickLook closing immediately upon trying to open

### ISSUE THREAD

**Issue by officalformat** [QL-Win/QuickLook#1379]
QuickLook is crashing/closing immediately upon opening. The process is shown in task manager for a brief second then vanishes. 

My previous install was from Windows Store, however I have switched to the MSI build to see if it fixes the issue (it did not)

 - OS Version: Windows 10 Home 22H2
 - QuickLook Version: 3.7.3 MSI

QuickLook is installed in the default directory, installing it in a custom directory makes no difference.

I use QuickLook to preview music samples before pulling them into a project in my DAW, so mostly MP3 and WAV files (not sure if that makes a difference.)

**Comment by rabelux** [comment]
Is there an exception log? Do you have problems starting quickook or is it the preview window that closes?

**Comment by officalformat** [comment]
> Is there an exception log? Do you have problems starting quickook or is it the preview window that closes?

I'm unsure how to generate/view the exception log (I'm not exactly fluent in coding), as soon as the process starts upon me hitting open it closes immediately. No preview window or "QuickLooks is already running" dialog popping up.

**Comment by rabelux** [comment]
> I'm unsure how to generate/view the exception log
It's explained in the wiki and also when creating an issue with the issue template

**Comment by officalformat** [comment]
> > I'm unsure how to generate/view the exception log
> 
> It's explained in the wiki and also when creating an issue with the issue template

Got it, the log was located in a different folder than shown in the wiki, but managed to get it.

========12/27/2023 1:24:33 PM========
System.TypeInitializationException: The type initializer for 'QuickLook.App' threw an exception. ---> System.Runtime.InteropServices.COMException: Class not registered

   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at QuickLook.NativeMethods.WMI.GetGPUNames()
   at QuickLook.Helpers.SystemHelper.IsGPUInBlacklist()
   at QuickLook.App..cctor()
   --- End of inner exception stack trace ---
   at QuickLook.TrayIconManager..ctor()
   at QuickLook.TrayIconManager.GetInstance()
   at QuickLook.App.RunListener(StartupEventArgs e)
   at QuickLook.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at QuickLook.App.Main()

**Comment by xupefei** [comment]
```
at System.Management.ManagementScope.Initialize()
at System.Management.ManagementObjectSearcher.Initialize()
at System.Management.ManagementObjectSearcher.Get()
at QuickLook.NativeMethods.WMI.GetGPUNames()
at QuickLook.Helpers.SystemHelper.IsGPUInBlacklist()
```
This method tries to identify your GPU model but fails. I have no idea how this can happen. Have you ever used cleaning software to remove any "garbage" in the system?

**Comment by officalformat** [comment]
> This method tries to identify your GPU model but fails. I have no idea how this can happen. Have you ever used cleaning software to remove any "garbage" in the system?

Never. My most recent software installs have been some new virtual instruments and FanControl, however I don't see how either of those would impact a GPU path. 

I recently updated my GPU drivers (GeForce RTX 3060 Ti), but the issue was occurring prior to and after the update.

**Comment by fiendish55** [comment]
Having the same problem, first time hitting spacebar in explorer with quicklook after opening pc ends up crashing quicklook.

**Comment by miyassin** [comment]
I've been having the same issue for a very long time. Is the app still actively developed?

**Comment by technobulb** [comment]
Same issue. Brand new PC, windows 11

**Comment by Traveritas** [comment]
+1

**Comment by emako** [comment]
COMException from WMI is fixed in nightly build.
https://github.com/QL-Win/QuickLook/releases

If there are other reasons for the crash, please open a new issue.
