### ISSUE TITLE
Persistent crash when opening quick look first time ie: after fresh boot of windows

### ISSUE THREAD

**Issue by nitro122** [QL-Win/QuickLook#1418]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
Basically, the app crashes whenever I opened after a windows fresh boot. I have tried reinstalling it. But the issue still remains

**To Reproduce**
 Fresh boot of windows

**Expected behavior**
I would like it not to crash when opening it for the first time

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 11 ]
 - QuickLook Version: [3.7.3 from Windows Store]

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by Roundlay** [comment]
This is a long unresolved, persistent issue, which likely won't be fixed any time soon. One possible remedy is discussed in https://github.com/QL-Win/QuickLook/issues/948#issuecomment-1651498435.

> Just an update, I restarted my computer after deleting the TextViewer plugin, and QuickLook is now working for most other file types, when I put the TextViewer plugin back in the QuickLook.Plugin folder, it started to crash again, so I guess it might be related to the TextViewer plugin?

**Comment by emako** [comment]
Could you provide your crash log in Event Viewer?

Such as:
![image](https://github.com/user-attachments/assets/4d481df3-0077-46d4-9b1c-ef2164ccf844)

**Comment by Roundlay** [comment]
Here are the three errors that were generated in Event Viewer after Quicklook crashed due to this issue.

**Source: Windows Error Reporting**

```
Log Name:      Application
Source:        Windows Error Reporting
Date:          20/12/2024 4:43:16 PM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      
User:
Computer:
Description:
Fault bucket 1677970416170767508, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: QuickLook.exe
P2: 3.7.3.0
P3: 637e91e1
P4: mscorlib
P5: 4.8.9290.0
P6: 67214b29
P7: 33e
P8: 2e
P9: System.ArgumentOutOfRange
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.93a0b160-c265-45e0-a64c-57d68e466fcf.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6dd8f43c-472d-4066-87c8-fa04d14d0aa8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.725a5fd6-9d01-4280-a273-3006b50657c1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.99ce7a5f-41c6-49ef-b53a-c6bd277e768f.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0d735292-2d94-4e86-8c96-0452f5e785a9.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_QuickLook.exe_b9a9634733af6392e4909db28a390526030_a7b0696f_ab6491a3-738a-4203-84b3-e5f9624c4619

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4134a62b-474a-4c49-aa97-df525e0d5a01
Report Status: 268435456
Hashed bucket: 01b52f68af812b2fc749593407791494
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" Guid="{0ead09bd-2157-539a-8d6d-c87f95b64d70}" />
    <EventID>1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-12-20T07:43:16.8979668Z" />
    <EventRecordID>1251</EventRecordID>
    <Correlation />
    <Execution ProcessID="14116" ThreadID="18364" />
    <Channel>Application</Channel>
    <Computer></Computer>
    <Security UserID="S-1-5-21-1739105479-1598266377-316182542-1001" />
  </System>
  <EventData>
    <Data Name="Bucket">1677970416170767508</Data>
    <Data Name="BucketType">5</Data>
    <Data Name="EventName">CLR20r3</Data>
    <Data Name="Response">Not available</Data>
    <Data Name="CabId">0</Data>
    <Data Name="P1">QuickLook.exe</Data>
    <Data Name="P2">3.7.3.0</Data>
    <Data Name="P3">637e91e1</Data>
    <Data Name="P4">mscorlib</Data>
    <Data Name="P5">4.8.9290.0</Data>
    <Data Name="P6">67214b29</Data>
    <Data Name="P7">33e</Data>
    <Data Name="P8">2e</Data>
    <Data Name="P9">System.ArgumentOutOfRange</Data>
    <Data Name="P10">
    </Data>
    <Data Name="AttachedFiles">
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.93a0b160-c265-45e0-a64c-57d68e466fcf.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6dd8f43c-472d-4066-87c8-fa04d14d0aa8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.725a5fd6-9d01-4280-a273-3006b50657c1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.99ce7a5f-41c6-49ef-b53a-c6bd277e768f.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0d735292-2d94-4e86-8c96-0452f5e785a9.tmp.xml</Data>
    <Data Name="StorePath">\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_QuickLook.exe_b9a9634733af6392e4909db28a390526030_a7b0696f_ab6491a3-738a-4203-84b3-e5f9624c4619</Data>
    <Data Name="AnalysisSymbol">
    </Data>
    <Data Name="Rechecking">0</Data>
    <Data Name="ReportId">4134a62b-474a-4c49-aa97-df525e0d5a01</Data>
    <Data Name="ReportStatus">268435456</Data>
    <Data Name="HashedBucket">01b52f68af812b2fc749593407791494</Data>
    <Data Name="CabGuid">0</Data>
  </EventData>
</Event>
```

**Source: Application Error**

```
Log Name:      Application
Source:        Application Error
Date:          20/12/2024 4:43:14 PM
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:
Computer:
Description:
Faulting application name: QuickLook.exe, version: 3.7.3.0, time stamp: 0x637e91e1
Faulting module name: KERNELBASE.dll, version: 10.0.26100.2454, time stamp: 0x398a1cce
Exception code: 0xe0434352
Fault offset: 0x00000000000c837a
Faulting process id: 0x3558
Faulting application start time: 0x1DB5279F3D662DE
Faulting application path: C:\Users\User\scoop\apps\quicklook\current\QuickLook.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4134a62b-474a-4c49-aa97-df525e0d5a01
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-12-20T07:43:14.8008413Z" />
    <EventRecordID>1250</EventRecordID>
    <Correlation />
    <Execution ProcessID="14116" ThreadID="18364" />
    <Channel>Application</Channel>
    <Computer></Computer>
    <Security UserID="S-1-5-21-1739105479-1598266377-316182542-1001" />
  </System>
  <EventData>
    <Data Name="AppName">QuickLook.exe</Data>
    <Data Name="AppVersion">3.7.3.0</Data>
    <Data Name="AppTimeStamp">637e91e1</Data>
    <Data Name="ModuleName">KERNELBASE.dll</Data>
    <Data Name="ModuleVersion">10.0.26100.2454</Data>
    <Data Name="ModuleTimeStamp">398a1cce</Data>
    <Data Name="ExceptionCode">e0434352</Data>
    <Data Name="FaultingOffset">00000000000c837a</Data>
    <Data Name="ProcessId">0x3558</Data>
    <Data Name="ProcessCreationTime">0x1db5279f3d662de</Data>
    <Data Name="AppPath">C:\Users\User\scoop\apps\quicklook\current\QuickLook.exe</Data>
    <Data Name="ModulePath">C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data Name="IntegratorReportId">4134a62b-474a-4c49-aa97-df525e0d5a01</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>
```

**Source: .NET Runtime**

```
Log Name:      Application
Source:        .NET Runtime
Date:          20/12/2024 4:43:14 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:
Description:
Application: QuickLook.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   at System.Collections.Generic.List`1[[System.Windows.Media.Composition.DUCE+Map+Entry, PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].RemoveAt(Int32)
   at System.Windows.Media.Composition.DUCE+Map.Remove(System.Object)
   at System.Windows.Media.Composition.DUCE+MultiChannelResource.ReleaseOnChannel(Channel)
   at System.Windows.Media.HostVisual.Disconnect(Channel, System.Windows.Threading.Dispatcher, ResourceHandle, ResourceHandle, MultiChannelResource)
   at System.Windows.Media.HostVisual.DoPendingDisconnect(Channel)
   at System.Windows.Media.HostVisual.DoDisconnectHostedVisual(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at QuickLook.App.Main()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-12-20T07:43:14.6422004Z" />
    <EventRecordID>1249</EventRecordID>
    <Correlation />
    <Execution ProcessID="13656" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer></Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: QuickLook.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   at System.Collections.Generic.List`1[[System.Windows.Media.Composition.DUCE+Map+Entry, PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].RemoveAt(Int32)
   at System.Windows.Media.Composition.DUCE+Map.Remove(System.Object)
   at System.Windows.Media.Composition.DUCE+MultiChannelResource.ReleaseOnChannel(Channel)
   at System.Windows.Media.HostVisual.Disconnect(Channel, System.Windows.Threading.Dispatcher, ResourceHandle, ResourceHandle, MultiChannelResource)
   at System.Windows.Media.HostVisual.DoPendingDisconnect(Channel)
   at System.Windows.Media.HostVisual.DoDisconnectHostedVisual(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at QuickLook.App.Main()

</Data>
  </EventData>
</Event>
```

**Comment by emako** [comment]
This question goes to track with #1648
