### ISSUE TITLE
QuickLook Fails to Preview HEIC Images After iOS 18 Update - ImageMagick.MagickCorruptImageErrorException

### ISSUE THREAD

**Issue by xDj4** [QL-Win/QuickLook#1470]
**Describe the bug**
Photos taken since updating to iOS 18 do not work with QuickLook. When attempting to preview, the following error message appears: "Failed to preview IMG_xxxx.HEIC."

**To Reproduce**

1. Take a photo on a device running iOS 18.
2. Transfer the HEIC image to a Windows machine.
3. Attempt to preview the image using QuickLook.
4. Observe the error message.

**Expected behavior**
The HEIC image should be previewed without errors in QuickLook, as it was prior to the iOS 18 update.

**Desktop (please complete the following information):**

- OS Version: Windows 10 [version number, e.g., 22H2]
- QuickLook Version: [version number, e.g., 3.7.1]

**Exception:**

```
========9/22/2024 11:36:28 AM========
ImageMagick.MagickCorruptImageErrorException: Invalid input: Unspecified: Metadata not correctly assigned to image `D:\...\IMG_1255.HEIC' @ error/heic.c/IsHeifSuccess/135
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadFile(IMagickSettings`1 settings)
   at ImageMagick.MagickImage.Read(String fileName, IMagickReadSettings`1 readSettings, Boolean ping)
   at QuickLook.Plugin.ImageViewer.MetaProvider.GetSize()
   at QuickLook.Plugin.ImageViewer.Plugin.Prepare(String path, ContextObject context)
   at QuickLook.ViewerWindow.BeginShow(IViewer matchedPlugin, String path, Action`2 exceptionHandler)
```

**Comment by iGeTT** [comment]
I have the same issue, however exception is different:

```
========19/10/2024 6:23:06 pm========
ImageMagick.MagickCorruptImageErrorException: Invalid input: Unspecified: Too many auxiliary image references `Z:\Alan\Episodes\24.10.14 – AU s02e17 (A4 Girls)\9\IMG_2115.HEIC' @ error/heic.c/IsHeifSuccess/135
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadFile(IMagickSettings`1 settings)
   at ImageMagick.MagickImage.Read(String fileName, IMagickReadSettings`1 readSettings, Boolean ping)
   at QuickLook.Plugin.ImageViewer.MetaProvider.GetSize()
   at QuickLook.Plugin.ImageViewer.Plugin.Prepare(String path, ContextObject context)
   at QuickLook.ViewerWindow.BeginShow(IViewer matchedPlugin, String path, Action`2 exceptionHandler)
```

**Comment by thanhvinh2213** [comment]
I have the same issue
