### ISSUE TITLE
An error occurred while previewing the .tif picture

### ISSUE THREAD

**Issue by trungdoan2507** [QL-Win/QuickLook#280]
**To Reproduce**
QuickLook can not preview this .tif file https://drive.google.com/open?id=0BzPldJlRgkgcRVBqWngyNE1Kakk
**Desktop (please complete the following information):**
 - OS Version: Windows 10 Insider Preview 17704.1000
 - QuickLook Version: 0.3.5-43-g8cd957d from AppVeyor

**Screenshots and Exception Log**
```
System.InvalidOperationException: Start may not be called on a task that was already started.
   at System.Threading.Tasks.Task.Start(TaskScheduler scheduler)
   at QuickLook.Plugin.ImageViewer.AnimatedImage.AnimatedImage.AnimationFrameIndexChanged(DependencyObject obj, DependencyPropertyChangedEventArgs ev)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at QuickLook.Plugin.ImageViewer.AnimatedImage.AnimatedImage.AnimationUriChanged(DependencyObject obj, DependencyPropertyChangedEventArgs ev)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at QuickLook.Plugin.ImageViewer.Plugin.View(String path, ContextObject context)
   at QuickLook.ViewerWindow.<>c__DisplayClass5_0.<BeginShow>b__0()
```

**Comment by xupefei** [comment]
I do not have the permission to your link. Do Can you check the sharing setting?

![image](https://user-images.githubusercontent.com/1687847/42725606-18c73a56-87b9-11e8-84bd-77075e216f7a.png)

**Comment by trungdoan2507** [comment]
Sorry! You can use this link to access the file: https://yadi.sk/d/wWSTXY1z3ZAp4Z
